# Generated by Django 5.1.8 on 2025-04-18 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('service_provider', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('repeat_frequency', models.CharField(choices=[('do_not_repeat', 'Do not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('bi-monthly', 'Bi-monthly'), ('annually', 'Annually'), ('custom', 'Custom')], default='do_not_repeat', max_length=50)),
                ('reminder', models.CharField(choices=[('no_reminder', 'No Reminder'), ('same_day', 'Remind on same day'), ('1_day_before', 'Remind 1 Day Before'), ('2_days_before', 'Remind 2 Days Before'), ('3_days_before', 'Remind 3 Days Before'), ('4_days_before', 'Remind 4 Days Before'), ('5_days_before', 'Remind 5 Days Before'), ('10_days_before', 'Remind 10 Days Before'), ('15_days_before', 'Remind 15 Days Before'), ('20_days_before', 'Remind 20 Days Before'), ('30_days_before', 'Remind 30 Days Before')], default='no_reminder', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=50)),
                ('auto_pay', models.BooleanField(default=False)),
                ('attach_photo', models.ImageField(blank=True, null=True, upload_to='bill_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
