# Generated by Django 5.1.8 on 2025-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='repeat_frequency',
            field=models.CharField(choices=[('do_not_repeat', 'Do not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('bi_monthly', 'Bi-monthly'), ('annually', 'Annually'), ('custom', 'Custom')], default='do_not_repeat', max_length=50),
        ),
    ]
