# Generated by Django 5.1.8 on 2025-04-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_bill_repeat_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
