# Generated by Django 5.1.8 on 2025-04-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_bill_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
