# Generated by Django 5.1.8 on 2025-04-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_bill_is_paid_bill_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='paid_at',
        ),
    ]
